apiVersion: apps/v1
kind: Deployment
metadata:
  name: udpecho
  labels:
    app: udpecho
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udpecho
  template:
    metadata:
      labels:
        app: udpecho
    spec:
      containers:
        - name: udpecho
          image: ghcr.io/emilzackrisson/trafficgenerators:latest
          command: ["/bin/udpecho"]
          args: ["1500"]
          ports:
            - containerPort: 1500
              protocol: UDP

---
apiVersion: v1
kind: Service
metadata:
  name: udpecho
spec:
  selector:
    app: udpecho
  ports:
    - protocol: UDP
      port: 1500
      targetPort: 1500
  type: NodePort
