#!/usr/bin/env python3

import argparse
import csv
import json
import os
import sys
from typing import Any, Optional
from parsers import parse_system_dir, parse_container_dir
from pathlib import Path

parser = argparse.ArgumentParser(
    prog="cgroup record parser"
)

parser.add_argument("record_dir")
parser.add_argument("-v", "--verbose", action='store_true')
parser.add_argument("--export-csv", action='store_true')



debug = False
def debug_log(out):
    if debug:
        print(out)

def verify_dir_is_valid(dir_path: Path) -> Optional[bool]:
    """Verify that specified directory is a directory generated by the cgroup recorder and is containing valid files."""
    meta_path = os.path.join(dir_path, "meta.txt")
    debug_log(f"Checking {meta_path}...")
    if not os.path.exists(meta_path):
        print("ERROR: meta.txt does not exist in specified directory")
        sys.exit(1)
    with open(meta_path, "r") as meta_file:
        first_line = meta_file.readline()
        if "cgroup v2 recorder" not in first_line:
            print("ERROR: meta.txt invalid!")
            sys.exit(1)
    debug_log("meta.txt is valid")

    dir_content = os.listdir(dir_path)
    if len(dir_content) < 2:
        print("ERROR: Specified directory does not contain any recorded stats.")
        sys.exit(1)

    return True

def flatten_for_csv(value: Any, prefix: str = "") -> dict[str, Any]:
    if isinstance(value, dict):
        flattened: dict[str, Any] = {}
        for key, nested_value in value.items():
            nested_prefix = f"{prefix}.{key}" if prefix else str(key)
            flattened.update(flatten_for_csv(nested_value, nested_prefix))
        return flattened

    column_name = prefix if prefix else "value"
    if isinstance(value, (int, float, str, bool)) or value is None:
        return {column_name: value}

    return {column_name: json.dumps(value)}

def write_metric_csv(out_path: Path, series: list[tuple[str, Any]]) -> None:
    rows: list[dict[str, Any]] = []
    discovered_columns: list[str] = []
    known_columns: set[str] = set()

    for snapshot, value in series:
        row = {"snapshot": snapshot}
        row.update(flatten_for_csv(value))
        rows.append(row)

        for key in row.keys():
            if key == "snapshot" or key in known_columns:
                continue
            known_columns.add(key)
            discovered_columns.append(key)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w", newline="") as csv_file:
        fieldnames = ["snapshot", *discovered_columns]
        writer = csv.DictWriter(csv_file, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)

def export_stats_to_csv(
    record_dir: Path,
    system_series: dict[str, list[tuple[str, Any]]],
    pod_series: dict[str, dict[str, dict[str, list[tuple[str, Any]]]]],
) -> None:
    for metric_name, series in system_series.items():
        write_metric_csv(Path(record_dir, "export", "system", f"{metric_name}.csv"), series)

    for pod_name, container_map in pod_series.items():
        for container_name, metric_map in container_map.items():
            for metric_name, series in metric_map.items():
                write_metric_csv(
                    Path(record_dir, "export", pod_name, container_name, f"{metric_name}.csv"),
                    series,
                )

def split_pod_container(dir_name: str) -> tuple[str, str]:
    if "_" not in dir_name:
        return dir_name, dir_name
    pod_name, container_name = dir_name.rsplit("_", 1)
    return pod_name, container_name

def append_metric(
    metrics: dict[str, list[Any]],
    series: dict[str, list[tuple[str, Any]]],
    snapshot: str,
    parsed_values: dict[str, Any],
) -> None:
    for key, value in parsed_values.items():
        metrics.setdefault(key, []).append(value)
        series.setdefault(key, []).append((snapshot, value))

def collect_snapshot_stats(
    snapshot_path: Path,
    snapshot: str,
    stats_dict: dict[str, Any],
    system_series: dict[str, list[tuple[str, Any]]],
    pod_series: dict[str, dict[str, dict[str, list[tuple[str, Any]]]]],
) -> None:
    system_path = Path(snapshot_path, "system")
    if not system_path.is_dir():
        return

    system_dict = parse_system_dir(system_path)
    append_metric(stats_dict["system"], system_series, snapshot, system_dict)

    for entry in snapshot_path.iterdir():
        if not entry.is_dir() or entry.name == "system":
            continue

        pod_name, container_name = split_pod_container(entry.name)
        container_dict = parse_container_dir(entry)

        pod_dict = stats_dict["pods"].setdefault(pod_name, {})
        container_stats = pod_dict.setdefault(container_name, {})

        pod_series_dict = pod_series.setdefault(pod_name, {})
        container_series = pod_series_dict.setdefault(container_name, {})

        append_metric(container_stats, container_series, snapshot, container_dict)

def walk_stats(dir_path: Path, export_csv: bool = False):
    dir_path = Path(dir_path)
    snapshots = sorted(entry.name for entry in dir_path.iterdir() if entry.is_dir())

    stats_dict = {}
    # stats_dict
    #   - system
    #       - cpu.pressure [list[dict]]
    #       - ...
    #   - pod-xyz
    #       - cpu.pressure [list]
    #       - memory.stats [list[dict]]
    #       - memory.current [list[int]]
    stats_dict["system"] = {}
    stats_dict["pods"] = {}

    system_series: dict[str, list[tuple[str, Any]]] = {}
    pod_series: dict[str, dict[str, dict[str, list[tuple[str, Any]]]]] = {}

    for snapshot in snapshots:
        snapshot_path = Path(dir_path, snapshot)
        collect_snapshot_stats(snapshot_path, snapshot, stats_dict, system_series, pod_series)

    if export_csv:
        export_stats_to_csv(dir_path, system_series, pod_series)

    debug_log(stats_dict)
    return stats_dict



def main():
    args = parser.parse_args()
    
    record_dir = args.record_dir

    if args.verbose:
        global debug
        debug = True

    verify_dir_is_valid(record_dir)
    walk_stats(record_dir, export_csv=args.export_csv)

if __name__ == "__main__":
    main()